In [2]:
import torch

In [3]:
torch.cuda.is_available()

False

In [4]:
x = torch.empty(5, 3)
print(x)

tensor([[5.3901e+19, 3.7975e-43, 5.3901e+19],
        [3.7975e-43, 5.3903e+19, 3.7975e-43],
        [5.3903e+19, 3.7975e-43, 5.3893e+19],
        [3.7975e-43, 5.3893e+19, 3.7975e-43],
        [5.3903e+19, 3.7975e-43, 5.3903e+19]])


In [5]:
x = torch.rand(5, 3)
print(x)

tensor([[0.1968, 0.0029, 0.6655],
        [0.0897, 0.9851, 0.6242],
        [0.7314, 0.2116, 0.0553],
        [0.0649, 0.2155, 0.1037],
        [0.6530, 0.4499, 0.3581]])


In [6]:
x = torch.zeros(5, 3, dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [8]:
points = torch.tensor([[1.0, 4.0], [2.0, 1.0], [3.0, 5.0]])
print(points.storage())

 1.0
 4.0
 2.0
 1.0
 3.0
 5.0
[torch.FloatStorage of size 6]

In [9]:
#手动索引到存储中
points_storage = points.storage()
print(points_storage[0])

1.0


In [ ]:
points = torch.tensor([[1.0, 4.0], [2.0, 1.0], [3.0, 5.0]])
points_storage = points.storage()
points_storage[0] = 2.0
points

In [11]:
points = torch.tensor([[1.0, 4.0], [2.0, 1.0], [3.0, 5.0]])
second_point = points[1]
second_point.storage_offset()

2

In [12]:
#张量尺寸信息与张量对象的shape属性中包含的信息相同
print(second_point.size())
print(second_point.shape)

torch.Size([2])
torch.Size([2])


In [13]:
#步长是一个元组，表示当索引在每个维度上增加1时必须跳过的存储中元素的数量。
print(points.stride())

(2, 1)


In [15]:
#对克隆的子向量进行操作不会影响到原向量
points = torch.tensor([[1.0, 4.0], [2.0, 1.0], [3.0, 5.0]])
second_point = points[1].clone()
second_point[0] = 10.0
print(points)
print(second_point)

tensor([[1., 4.],
        [2., 1.],
        [3., 5.]])
tensor([10.,  1.])


In [20]:
#转置操作得到的新向量与原向量共用一个存储，只是步长和尺寸不同
points = torch.tensor([[1.0, 4.0], [2.0 ,1.0], [3.0, 5.0]])
points_t = points.t()
print(points)
print(points_t)
print(points.size(), points.stride())
print(points_t.size(), points_t.stride())
print(id(points.storage()) == id(points_t.storage()))

tensor([[1., 4.],
        [2., 1.],
        [3., 5.]])
tensor([[1., 2., 3.],
        [4., 1., 5.]])
torch.Size([3, 2]) (2, 1)
torch.Size([2, 3]) (1, 2)
True


In [19]:
#在PyTorch中进行转置不仅限于矩阵（即二维数组）。以翻转三维数组的步长和尺寸为例，你可以通过指定应需要转置的两个维度来转置多维数组
some_tensor = torch.ones(3, 4, 5)
print(some_tensor.shape, some_tensor.stride())
some_tensor_t = some_tensor.transpose(0, 2)
print(some_tensor_t.shape, some_tensor_t.stride())

torch.Size([3, 4, 5]) (20, 5, 1)
torch.Size([5, 4, 3]) (1, 5, 20)


In [28]:
#比较连续性
print(points.is_contiguous(), points_t.is_contiguous())

True False


In [33]:
points_storage = points.storage()
points_t_cont = points_t.contiguous()
points_t_cont_storage = points_t_cont.storage()
print(points_storage, points_t_cont_storage, sep='\n')
print(id(points_storage) == id(points_t_cont_storage))

1.0
 4.0
 2.0
 1.0
 3.0
 5.0
[torch.FloatStorage of size 6]
 1.0
 2.0
 3.0
 4.0
 1.0
 5.0
[torch.FloatStorage of size 6]
False


In [34]:
double_points = torch.ones(10, 2, dtype=torch.double)
short_points = torch.tensor([[1, 2], [3, 4]], dtype=torch.short)

In [35]:
print(double_points.dtype, short_points.dtype)

torch.float64 torch.int16


In [38]:
#转换数据类型的to和type方法
points = torch.randn(5, 3)
print(points.dtype)
points = points.to(torch.double)
print(points.dtype)
points = points.type(torch.float)
print(points.dtype)

torch.float32
torch.float64
torch.float32


In [43]:
#torch和numpy的数据转换
import numpy as np
points = torch.ones(3, 5)
points_np = points.numpy()
print(points_np)
points = torch.from_numpy(points_np)
print(points)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]] float32
tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])


In [52]:
#序列化pytorch张量
points = torch.ones(3, 5)
torch.save(points, './data/points.t')

points_f = points
with open('./data/points_f.t', 'wb') as f:
    torch.save(points, f)

print(points)
print(points_f)

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])
tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])


In [54]:
points_f = points = torch.randn(3, 5)
print(points)
print(points_f)

tensor([[ 0.3242,  0.0867, -0.5794,  0.3694, -0.6076],
        [ 0.6449, -1.3153,  0.7836, -0.6716, -1.4027],
        [-1.5045, -0.7690,  0.5892, -0.2339,  0.9489]])
tensor([[ 0.3242,  0.0867, -0.5794,  0.3694, -0.6076],
        [ 0.6449, -1.3153,  0.7836, -0.6716, -1.4027],
        [-1.5045, -0.7690,  0.5892, -0.2339,  0.9489]])


In [55]:
#反序列化pytorch张量
points = torch.load('./data/points.t')

with open('./data/points_f.t', 'rb') as f:
    points_f = torch.load(f)

print(points)
print(points_f)

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])
tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])


In [76]:
#练习
a = torch.tensor(list(range(9)))
print(a.size(), a.stride(), a.storage_offset())

torch.Size([9]) (1,) 0


In [65]:
b = a.reshape(3, 3)
print(b[1,1])
print(b.size(), b.stride(), b.storage_offset())

tensor(4)
torch.Size([3, 3]) (3, 1) 0


In [67]:
c = b[1:, 1:]
print(c)
print(c.size(), c.stride(), c.storage_offset())

tensor([[4, 5],
        [7, 8]])
torch.Size([2, 2]) (3, 1) 4


In [79]:
d = torch.sqrt(a.to(torch.double))
print(d)
a = a.to(torch.double)
torch.sqrt_(a)
print(a)

tensor([0.0000, 1.0000, 1.4142, 1.7321, 2.0000, 2.2361, 2.4495, 2.6458, 2.8284],
       dtype=torch.float64)
tensor([0.0000, 1.0000, 1.4142, 1.7321, 2.0000, 2.2361, 2.4495, 2.6458, 2.8284],
       dtype=torch.float64)
